services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
    - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: yes
    command: start-notebook.py --NotebookApp.token=''
  clickHouse:
    image: clickhouse/clickhouse-server
    ports:
    - "18123:8123"
    - "19000:9000"
    environment:
      - CLICKHOUSE_PASSWORD=test