services:
  notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - mysql
      - clickhouse
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      - CLICKHOUSE_PASSWORD=password
    ports:
      - "8443:8443"
      - "9000:9000"
